SERVER:
  port: 8001
  host: 'localhost'
  reload: true


DATABASE:
  connections:
    mysql:
      engine: 'tortoise.backends.mysql'
      credentials:
        host: 'localhost'
        port: 3306
        user: 'root'
        password: 'root'
        database: 'database'
  apps:
    auth:
      models: ['components.auth.models']
      default_connection: 'mysql'


AUTH:
  algorithm: 'HS256'
  secret_key: '062843e82369cbe2a3f15c25b24e4c7300c4f6d0c2059a2d76e5082b526f636e'
